In [1]:
import numpy as np 


In [2]:
#scenario 1

a1=np.arange(8).reshape(2,4)
a2=np.arange(8,16).reshape(2,4)

print(a1)
print(a2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [3]:
a1+a2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [4]:
#scenario 2
a3=np.arange(9).reshape(3,3)
a4=np.arange(3).reshape(1,3)

print(a3,a4)

[[0 1 2]
 [3 4 5]
 [6 7 8]] [[0 1 2]]


In [5]:
a3+a4

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [6]:
np.random.random()

0.7997220408752482

In [8]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [9]:
np.random.uniform(1,100)

72.31212485077366

In [10]:
np.random.uniform(1,100,10).reshape(2,5)

array([[ 1.01132311, 30.93092469, 15.52883319, 10.14152088, 19.43976093],
       [35.21051198, 40.27997995, 54.34285667, 42.50025693, 68.83673054]])

In [12]:
np.random.randint(1,10,15).reshape(3,5)

array([[8, 1, 7, 8, 7],
       [2, 1, 2, 9, 9],
       [4, 9, 8, 4, 7]], dtype=int32)

In [14]:
a=np.random.randint(1,10,6)
a

array([5, 1, 4, 3, 1, 5], dtype=int32)